import { useState } from 'react';
import { FileText, Download, ChevronDown, ChevronRight, CheckCircle2, PenLine, Bookmark } from 'lucide-react';
import type { PolicyDocument, PolicySection } from '../../types';

const statusMeta: Record<string, { bg: string; color: string; label: string; icon: typeof CheckCircle2 }> = {
  new:      { bg: '#F0FDF4', color: '#16A34A', label: 'New',      icon: PenLine },
  revised:  { bg: '#FFFBEB', color: '#D97706', label: 'Revised',  icon: PenLine },
  retained: { bg: '#EFF6FF', color: '#2563EB', label: 'Retained', icon: Bookmark },
};

function SectionRow({ section }: { section: PolicySection }) {
  const [expanded, setExpanded] = useState(false);
  const s = statusMeta[section.status] || statusMeta.new;

  return (
    <div className="policy-row-shell">
      <button
        onClick={() => setExpanded(!expanded)}
        aria-expanded={expanded}
        className="disclosure-trigger"
      >
        <span style={{ fontFamily: 'var(--font-mono)', fontSize: 12, fontWeight: 700, color: '#0076A8', minWidth: 28 }}>
          {section.sectionNumber}
        </span>
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--slate-800)' }}>{section.title}</div>
          <div style={{ fontSize: 11, color: 'var(--slate-500)', marginTop: 1 }}>Clause: {section.clauseRef}</div>
        </div>
        <span style={{
          fontSize: 10, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.05em',
          padding: '2px 6px', borderRadius: 2, background: s.bg, color: s.color,
        }}>{s.label}</span>
        {expanded ? <ChevronDown size={14} style={{ color: 'var(--slate-400)' }} /> : <ChevronRight size={14} style={{ color: 'var(--slate-400)' }} />}
      </button>
      {expanded && (
        <div className="disclosure-panel">
          <p style={{ fontSize: 13, color: 'var(--slate-700)', lineHeight: 1.6, whiteSpace: 'pre-wrap' }}>{section.content}</p>
        </div>
      )}
    </div>
  );
}

function PolicyCard({ doc }: { doc: PolicyDocument }) {
  const [expanded, setExpanded] = useState(false);

  const handleDownload = () => {
    const lines: string[] = [];
    lines.push('='.repeat(80));
    lines.push(doc.title.toUpperCase());
    lines.push('='.repeat(80));
    lines.push('');
    lines.push(`Standard:        ${doc.standardName} (${doc.standardCode})`);
    lines.push(`Version:         ${doc.version}`);
    lines.push(`Effective Date:  ${doc.effectiveDate}`);
    lines.push(`Compliance:      ${doc.complianceScore}%`);
    lines.push(`Gaps Addressed:  ${doc.gapsAddressed}`);
    lines.push('');
    lines.push('-'.repeat(80));
    lines.push('EXECUTIVE SUMMARY');
    lines.push('-'.repeat(80));
    lines.push(doc.summary);
    lines.push('');

    for (const section of doc.sections) {
      lines.push('-'.repeat(80));
      lines.push(`${section.sectionNumber}. ${section.title}`);
      lines.push(`   Clause Reference: ${section.clauseRef} | Status: ${section.status.toUpperCase()}`);
      lines.push('-'.repeat(80));
      lines.push(section.content);
      lines.push('');
    }

    lines.push('='.repeat(80));
    lines.push('END OF POLICY DOCUMENT');
    lines.push(`Generated by ComplianceGPT Policy Generator Agent`);
    lines.push(`Date: ${new Date().toISOString()}`);
    lines.push('='.repeat(80));

    const content = lines.join('\n');
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${doc.standardCode}_Policy_v${doc.version}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div style={{ border: '1px solid var(--border)', borderRadius: 'var(--radius-lg)', background: 'var(--white)', overflow: 'hidden' }}>
      <div style={{ padding: '16px', display: 'flex', alignItems: 'center', gap: 12 }}>
        <div style={{
          width: 40, height: 40, borderRadius: 8, display: 'flex', alignItems: 'center', justifyContent: 'center',
          background: '#E6F4FA', color: '#0076A8', flexShrink: 0,
        }}>
          <FileText size={20} />
        </div>
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ fontSize: 14, fontWeight: 700, color: 'var(--slate-800)' }}>{doc.title}</div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 2, flexWrap: 'wrap' }}>
            <span style={{ fontFamily: 'var(--font-mono)', fontSize: 11, fontWeight: 600, color: '#0076A8' }}>
              {doc.standardCode.replace('ISO', 'ISO ')}
            </span>
            <span style={{ fontSize: 11, color: 'var(--slate-500)' }}>v{doc.version}</span>
            <span style={{
              fontSize: 10, fontWeight: 700, padding: '2px 6px', borderRadius: 2,
              background: '#F0FDF4', color: '#16A34A',
            }}>
              {doc.complianceScore}% Compliant
            </span>
            <span style={{ fontSize: 11, color: 'var(--slate-500)' }}>
              {doc.gapsAddressed} gaps addressed
            </span>
          </div>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
          <button
            onClick={() => setExpanded(!expanded)}
            aria-expanded={expanded}
            style={{
              padding: '6px 12px', borderRadius: 999, fontSize: 12, fontWeight: 600,
              border: '1px solid var(--border)', background: 'var(--white)', color: 'var(--slate-600)',
              cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 4,
            }}
          >
            {expanded ? 'Collapse' : 'Preview'}
            {expanded ? <ChevronDown size={12} /> : <ChevronRight size={12} />}
          </button>
          <button
            onClick={handleDownload}
            style={{
              padding: '6px 12px', borderRadius: 999, fontSize: 12, fontWeight: 600,
              border: '1px solid #0076A8', background: '#0076A8', color: '#FFFFFF',
              cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 4,
            }}
          >
            <Download size={12} /> Download
          </button>
        </div>
      </div>

      {expanded && (
        <div style={{ borderTop: '1px solid var(--border)', padding: '12px 16px' }}>
          <div style={{
            padding: '10px 14px', background: '#F0FDF4', borderRadius: 'var(--radius-lg)',
            border: '1px solid #BBF7D0', fontSize: 13, color: '#166534', lineHeight: 1.6, marginBottom: 12,
          }}>
            {doc.summary}
          </div>
          <div style={{ fontSize: 11, fontWeight: 700, color: 'var(--slate-500)', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 8 }}>
            Policy Sections ({doc.sections.length})
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
            {doc.sections.map((s) => (
              <SectionRow key={s.sectionNumber} section={s} />
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

export default function PolicyGeneratorPanel({ documents }: { documents: PolicyDocument[] }) {
  const totalSections = documents.reduce((sum, d) => sum + d.sections.length, 0);
  const totalGapsAddressed = documents.reduce((sum, d) => sum + d.gapsAddressed, 0);
  const newSections = documents.reduce((sum, d) => sum + d.sections.filter(s => s.status === 'new').length, 0);
  const revisedSections = documents.reduce((sum, d) => sum + d.sections.filter(s => s.status === 'revised').length, 0);

  const handleDownloadAll = () => {
    for (const doc of documents) {
      const lines: string[] = [];
      lines.push('='.repeat(80));
      lines.push(doc.title.toUpperCase());
      lines.push('='.repeat(80));
      lines.push('');
      lines.push(`Standard:        ${doc.standardName} (${doc.standardCode})`);
      lines.push(`Version:         ${doc.version}`);
      lines.push(`Effective Date:  ${doc.effectiveDate}`);
      lines.push(`Compliance:      ${doc.complianceScore}%`);
      lines.push(`Gaps Addressed:  ${doc.gapsAddressed}`);
      lines.push('');
      lines.push('-'.repeat(80));
      lines.push('EXECUTIVE SUMMARY');
      lines.push('-'.repeat(80));
      lines.push(doc.summary);
      lines.push('');

      for (const section of doc.sections) {
        lines.push('-'.repeat(80));
        lines.push(`${section.sectionNumber}. ${section.title}`);
        lines.push(`   Clause Reference: ${section.clauseRef} | Status: ${section.status.toUpperCase()}`);
        lines.push('-'.repeat(80));
        lines.push(section.content);
        lines.push('');
      }

      lines.push('='.repeat(80));
      lines.push('END OF POLICY DOCUMENT');
      lines.push(`Generated by ComplianceGPT Policy Generator Agent`);
      lines.push(`Date: ${new Date().toISOString()}`);
      lines.push('='.repeat(80));

      const content = lines.join('\n');
      const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${doc.standardCode}_Policy_v${doc.version}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }
  };

  const summaryCards = [
    { label: 'Policies Generated', value: documents.length, color: '#0076A8' },
    { label: 'Total Sections', value: totalSections, color: '#5C5C5C' },
    { label: 'Gaps Addressed', value: totalGapsAddressed, color: '#16A34A' },
    { label: 'New Sections', value: newSections, color: '#16A34A' },
    { label: 'Revised Sections', value: revisedSections, color: '#D97706' },
    { label: 'Compliance Target', value: '100%', color: '#16A34A' },
  ];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
      <div className="summary-grid-responsive">
        {summaryCards.map(c => (
          <div key={c.label} className="summary-stat-card">
            <div className="summary-stat-value" style={{ color: c.color }}>{c.value}</div>
            <div className="summary-stat-label">{c.label}</div>
          </div>
        ))}
      </div>

      <div className="report-banner report-banner-success" style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
        <CheckCircle2 size={16} style={{ flexShrink: 0 }} />
        <span>
          <strong>{documents.length} policy documents</strong> generated targeting <strong>100% compliance</strong>.
          All identified gaps have been addressed with specific policy provisions.
          Download individual policies or use "Download All" to get the complete set.
        </span>
      </div>

      <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
        <button
          onClick={handleDownloadAll}
          style={{
            padding: '8px 18px', borderRadius: 999, fontSize: 13, fontWeight: 700,
            border: '1px solid #0076A8', background: '#0076A8', color: '#FFFFFF',
            cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 6,
          }}
        >
          <Download size={14} /> Download All Policies
        </button>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
        {documents.map(doc => (
          <PolicyCard key={doc.id} doc={doc} />
        ))}
      </div>
    </div>
  );
}
